insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        1,
        'Victoir',
        'Sturdy',
        'Mexico',
        6085.71,
        2,
        'Divorced',
        'M',
        47039.28
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        2,
        'Papageno',
        'Isakovic',
        'Peru',
        6671.14,
        1,
        'Single',
        'M',
        38739.26
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        3,
        'Benedicto',
        'Crosby',
        'Mexico',
        4323.93,
        2,
        'Divorced',
        'M',
        22920.98
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        4,
        'Hyatt',
        'Keepence',
        'France',
        4236.26,
        1,
        'Married',
        'M',
        49479.96
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        5,
        'Nikkie',
        'Keysel',
        'Mexico',
        5705.48,
        2,
        'Single',
        'F',
        71413.7
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        6,
        'Teressa',
        'Dyer',
        'Brazil',
        8389.08,
        5,
        'Single',
        'F',
        12140.15
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        7,
        'Thibaud',
        'Wordsley',
        'Nigeria',
        2070.31,
        5,
        'Single',
        'M',
        31635.73
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        8,
        'Ingar',
        'Prantoni',
        'Canada',
        7971.5,
        1,
        'Married',
        'M',
        70443.82
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        9,
        'Valli',
        'Chalk',
        'China',
        4423.93,
        1,
        'Divorced',
        'F',
        67814.67
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        10,
        'Domenic',
        'Skipperbottom',
        'Mexico',
        6414.39,
        4,
        'Single',
        'M',
        86375.5
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        11,
        'Richmound',
        'O''Fallon',
        'China',
        1107.26,
        3,
        'Married',
        'M',
        84487.11
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        12,
        'Carrol',
        'Bernaciak',
        'Sweden',
        7846.01,
        3,
        'Married',
        'M',
        78335.59
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        13,
        'Drusie',
        'Burchill',
        'Poland',
        1462.09,
        3,
        'Divorced',
        'F',
        44348.78
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        14,
        'Germain',
        'Pyrah',
        'Sweden',
        7464.41,
        3,
        'Divorced',
        'F',
        60131.25
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        15,
        'Rustin',
        'Osgerby',
        'Russia',
        6002.92,
        4,
        'Married',
        'M',
        41471.23
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        16,
        'Bogart',
        'Chrismas',
        'Indonesia',
        6336.75,
        3,
        'Divorced',
        'M',
        31031.27
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        17,
        'Rori',
        'Linton',
        'El Salvador',
        3170.59,
        3,
        'Single',
        'F',
        44379.32
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        18,
        'Mukhes',
        'Ambani',
        'India',
        1100.87,
        1,
        'Married',
        'M',
        41991.47
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        19,
        'Lewes',
        'Dorro',
        'Indonesia',
        6926.74,
        1,
        'Single',
        'M',
        20000
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        20,
        'Kristin',
        'Valero',
        'Sweden',
        4006.84,
        3,
        'Divorced',
        'F',
        10269.59
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        21,
        'Jorrie',
        'Scirman',
        'China',
        7432.39,
        5,
        'Single',
        'F',
        19907.51
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        22,
        'Zacharias',
        'Veillard',
        'America',
        25000,
        1,
        'Married',
        'M',
        83530.79
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        23,
        'Gothart',
        'De Giorgis',
        'Croatia',
        8505.86,
        5,
        'Married',
        'M',
        7686.56
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        24,
        'Masha',
        'Akehurst',
        'China',
        218.13,
        4,
        'Divorced',
        'F',
        85674.34
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        25,
        'Ayn',
        'Lansly',
        'China',
        2977.69,
        3,
        'Single',
        'F',
        15312.27
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        26,
        'Clyve',
        'Rivers',
        'Indonesia',
        5661.38,
        1,
        'Single',
        'M',
        37961.48
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        27,
        'Jenda',
        'Urion',
        'China',
        2122.17,
        4,
        'Married',
        'F',
        58868.45
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        28,
        'Neysa',
        'Seamons',
        'Indonesia',
        5153.8,
        1,
        'Married',
        'F',
        84280.88
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        29,
        'Bobbie',
        'Blackett',
        'Thailand',
        9835.92,
        2,
        'Single',
        'F',
        25169.69
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        30,
        'Eddie',
        'Honisch',
        'Indonesia',
        6249.28,
        4,
        'Divorced',
        'M',
        33307.71
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        31,
        'Alford',
        'McNysche',
        'Brazil',
        2045.45,
        2,
        'Single',
        'M',
        15768.29
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        32,
        'Cherri',
        'Ohrtmann',
        'Peru',
        9376.56,
        5,
        'Divorced',
        'F',
        24000
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        33,
        'Leonard',
        'Fernie',
        'Czech Republic',
        6088.46,
        2,
        'Divorced',
        'M',
        300
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        34,
        'Galen',
        'Cadwell',
        'China',
        9785.83,
        4,
        'Divorced',
        'M',
        4500
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        35,
        'Katherine',
        'Parrish',
        'Russia',
        9573.35,
        5,
        'Divorced',
        'F',
        24000
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        36,
        'Craig',
        'Measen',
        'Brazil',
        8911.96,
        4,
        'Single',
        'M',
        92091.37
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        37,
        'Lem',
        'Whicher',
        'Portugal',
        7277.16,
        4,
        'Single',
        'M',
        4470.61
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        38,
        'Shandeigh',
        'Weich',
        'China',
        5587.82,
        3,
        'Married',
        'F',
        19263.1
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        39,
        'Christoph',
        'Rainey',
        'Greece',
        5648.48,
        4,
        'Married',
        'M',
        70343.4
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        40,
        'Christoper',
        'Gibbetts',
        'Portugal',
        5767.88,
        1,
        'Single',
        'M',
        36334.33
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        41,
        'Winnie',
        'Emmanuele',
        'China',
        6375.01,
        2,
        'Married',
        'F',
        82403.19
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        42,
        'Meg',
        'Sen',
        'India',
        4590.99,
        2,
        'Single',
        'M',
        19737.15
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        43,
        'Gardie',
        'Pentony',
        'Gabon',
        9699.67,
        5,
        'Divorced',
        'M',
        76063.0
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        44,
        'Charyl',
        'Matis',
        'America',
        7010.36,
        1,
        'Married',
        'F',
        29824.61
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        45,
        'Robina',
        'Bengefield',
        'America',
        25000,
        2,
        'Married',
        'F',
        56285.54
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        46,
        'Claudia',
        'Robley',
        'France',
        5628.01,
        4,
        'Married',
        'F',
        73696.77
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        47,
        'Madison',
        'Shorto',
        'Portugal',
        6952.43,
        2,
        'Married',
        'M',
        79040.11
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        48,
        'Jory',
        'Robbs',
        'Albania',
        2199.0,
        3,
        'Divorced',
        'M',
        75977.98
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        49,
        'Maddy',
        'Fredson',
        'America',
        5379.78,
        5,
        'Married',
        'M',
        46577.09
    );
insert into customer (
        cust_id,
        cust_fname,
        cust_lname,
        territory,
        cred_lmt,
        mngr_id,
        marital_status,
        sex,
        income
    )
values (
        50,
        'Harman',
        'Clementson',
        'China',
        6267.07,
        1,
        'Divorced',
        'M',
        66016.75
    );